import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP SUPPORT
 */
public class ContadorDinamico1 extends javax.swing.JFrame {
    int contador;
    int incrementador;


    public ContadorDinamico1() {
        initComponents();
        modal();
    }
    
    private void modal(){
        JOptionPane.showMessageDialog(new JFrame(), "Hola: Erik","Titulo del modal",JOptionPane.OK_OPTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfIncrementador = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbContador1 = new javax.swing.JLabel();
        btnAumentar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        lbContador2 = new javax.swing.JLabel();
        btnDisminuir1 = new javax.swing.JButton();
        tfincrementador = new javax.swing.JTextField();
        btnCargarValor = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        tfIncrementador.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Contador Dinámico");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImaContadorD/6341774.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(553, 512));
        jLabel2.setMinimumSize(new java.awt.Dimension(553, 512));
        jLabel2.setPreferredSize(new java.awt.Dimension(553, 512));

        lbContador1.setBackground(new java.awt.Color(255, 255, 255));
        lbContador1.setFont(new java.awt.Font("Yu Gothic UI", 0, 70)); // NOI18N
        lbContador1.setForeground(new java.awt.Color(0, 0, 0));
        lbContador1.setText("0");
        lbContador1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), null));

        btnAumentar.setBackground(new java.awt.Color(153, 153, 153));
        btnAumentar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAumentar.setForeground(new java.awt.Color(51, 51, 51));
        btnAumentar.setText("Aumentar");
        btnAumentar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAumentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAumentarActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(153, 153, 153));
        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(51, 51, 51));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        lbContador2.setBackground(new java.awt.Color(255, 255, 255));
        lbContador2.setFont(new java.awt.Font("Yu Gothic UI", 0, 70)); // NOI18N
        lbContador2.setForeground(new java.awt.Color(0, 0, 0));
        lbContador2.setText("0");
        lbContador2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), null));

        btnDisminuir1.setBackground(new java.awt.Color(153, 153, 153));
        btnDisminuir1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDisminuir1.setForeground(new java.awt.Color(51, 51, 51));
        btnDisminuir1.setText("Disminuir");
        btnDisminuir1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDisminuir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisminuir1ActionPerformed(evt);
            }
        });

        tfincrementador.setBackground(new java.awt.Color(255, 255, 255));
        tfincrementador.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tfincrementador.setForeground(new java.awt.Color(0, 0, 0));
        tfincrementador.setText("0");
        tfincrementador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfincrementadorActionPerformed(evt);
            }
        });

        btnCargarValor.setBackground(new java.awt.Color(153, 153, 153));
        btnCargarValor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCargarValor.setForeground(new java.awt.Color(0, 0, 0));
        btnCargarValor.setText("Cargar");
        btnCargarValor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCargarValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarValorActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Incrementador");

        javax.swing.GroupLayout tfIncrementadorLayout = new javax.swing.GroupLayout(tfIncrementador);
        tfIncrementador.setLayout(tfIncrementadorLayout);
        tfIncrementadorLayout.setHorizontalGroup(
            tfIncrementadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tfIncrementadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tfIncrementadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tfIncrementadorLayout.createSequentialGroup()
                        .addGap(0, 156, Short.MAX_VALUE)
                        .addGroup(tfIncrementadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tfIncrementadorLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(139, 139, 139))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tfIncrementadorLayout.createSequentialGroup()
                                .addComponent(btnDisminuir1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addGroup(tfIncrementadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(tfIncrementadorLayout.createSequentialGroup()
                                        .addComponent(btnAumentar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(183, 183, 183))
                                    .addGroup(tfIncrementadorLayout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addGroup(tfIncrementadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(tfIncrementadorLayout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addContainerGap())
                                            .addGroup(tfIncrementadorLayout.createSequentialGroup()
                                                .addComponent(tfincrementador)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnCargarValor, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(29, 29, 29))))))))
                    .addGroup(tfIncrementadorLayout.createSequentialGroup()
                        .addGroup(tfIncrementadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbContador2))
                        .addGap(102, 102, 102)
                        .addComponent(lbContador1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tfIncrementadorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(242, 242, 242))
        );
        tfIncrementadorLayout.setVerticalGroup(
            tfIncrementadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tfIncrementadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(tfIncrementadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tfIncrementadorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tfIncrementadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCargarValor)
                            .addComponent(tfincrementador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(84, 84, 84))
                    .addGroup(tfIncrementadorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(tfIncrementadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbContador1)
                    .addComponent(lbContador2))
                .addGap(18, 18, 18)
                .addGroup(tfIncrementadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDisminuir1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAumentar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tfIncrementador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tfIncrementador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAumentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAumentarActionPerformed
        incrementador = Integer.parseInt(tfincrementador.getText());
        contador = contador + incrementador;
        lbContador1.setText(String.valueOf (contador));
        lbContador2.setText(String.valueOf (contador));
                
        System.out.println("Suma: "+contador);
        
    }//GEN-LAST:event_btnAumentarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        contador = 0;
        lbContador1.setText(String.valueOf (contador));;
        
        lbContador2.setText(String.valueOf (contador));
        System.out.println("Limpiar: "+contador);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnDisminuir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisminuir1ActionPerformed
        incrementador = Integer.parseInt(tfincrementador.getText());
        contador = contador - incrementador;
        lbContador1.setText(String.valueOf (contador));;
        
        lbContador2.setText(String.valueOf (contador));
        System.out.println("Resta: "+contador);
        
    }//GEN-LAST:event_btnDisminuir1ActionPerformed

    private void tfincrementadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfincrementadorActionPerformed

        lbContador1.setText(String.valueOf(contador));
        lbContador2.setText(String.valueOf(contador));
    }//GEN-LAST:event_tfincrementadorActionPerformed

    private void btnCargarValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarValorActionPerformed
   
    }//GEN-LAST:event_btnCargarValorActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContadorDinamico1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContadorDinamico1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContadorDinamico1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContadorDinamico1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContadorDinamico1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAumentar;
    private javax.swing.JButton btnCargarValor;
    private javax.swing.JButton btnDisminuir1;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbContador1;
    private javax.swing.JLabel lbContador2;
    private javax.swing.JPanel tfIncrementador;
    private javax.swing.JTextField tfincrementador;
    // End of variables declaration//GEN-END:variables
}
